launcher_args: {experiment_name: predict_msg,
  script_name: "src/ms_pred/clip/clip_predict.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 4, job-name: forward_train, mem-per-cpu: 8G, 
    nodelist: 'node[1236]', time: '1-18:00:00'}

  gpu: [true]

  num-workers: [16]
  batch-size: [256]

  dataset-name: [msg]
  split-name: [split_msg.tsv]
  subset-datasets: [filtered_data]

  dataset-labels: [labels.tsv]
  # dataset-labels: [labels_confs.pkl]
  checkpoint: [/home/weiwentao/workspace/ms-pred/results/clip_msg_local/split_msg_rnd1/version_16/best.ckpt]

  save-dir: [/home/weiwentao/workspace/ms-pred/results/clip_msg_local/split_msg_rnd1/version_16/]
  binned-out: [true]

  embed-adducts: [true]
  inject-early: [true]

iterative_args:
  -  split-name: [split_fitered_data.tsv]
     subset-datasets: [filtered_data]
    #  save-dir: [split_msg_rnd1]
     magma-dag-folder: [/data/weiwentao/ms-pred/results/dag_msg_train/split_msg_rnd1/preds_train_20_inten_corrected/]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd2]
  #    seed: [2]
  #    magma-dag-folder: [results/dag_canopus_train_public/split_1_rnd2/preds_train_100_inten/]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd3]
  #    seed: [3]
  #    magma-dag-folder: [results/dag_canopus_train_public/split_1_rnd3/preds_train_100_inten/]
