launcher_args: {experiment_name: clip_train_canopus_local,
  script_name: "src/ms_pred/clip/clip_train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [4]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
    nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  num-gpu: [1]

  seed: [42]
  num-workers: [16]
  batch-size: [128]
  max-epochs: [200]
  # debug-test: [true]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv]

  learning-rate: [0.00005]
  lr-decay-rate: [0.825]  # 0.825

  dropout: [0.1]
  mpnn-type: [GGNN]
  pe-embed-k: [14]  # 0
  pool-op: [avg]
  hidden-size: [512]   # 128 1024  
  weight-decay: [1e-7]

  frag-set-layers: [3] #[1]
  loss-fn: [cosine]

  root-encode: [egt2d]  # egt2d, egt3d
  mabnet-layers: [4]
  mabnet-heads: [16]
  edge-update: [true]

  projection-dim: [512]

  inject-early: [true]  # false
  binned-targs: [true] 
  embed-adduct: [true]
  encode-forms: [true]
  patience: [50]

  grad-accumulate: [1]
  add-hs: [true]

  local-contra: [true]
  local-weight: [0.5]
  local-threshold: [0.0]
  frag-supervised: [true]
  frag-path: [/home/weiwentao/workspace/ms-pred/data/spec_datasets/msg/frags_index_map_observed.hdf5]
  frag-supervised-weight: [0.5]
  local-start-epochs: [10]

  dataset-labels: [labels_confs.pkl]
  # mol-ckpt: [/home/weiwentao/workspace/ms-pred/results/egt_pretrain/2025_08_22-1743_231522_561f4581f1413619be1abf3dc8cc43db/version_0/best.ckpt]
  spec-ckpt: [/home/weiwentao/workspace/DreaMS/dreams/models/pretrained/ssl_model.ckpt]
  dreams: [true]
  frozen-dreams: [true]
  frozen-epochs: [3]


iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
    #  seed: [1]
     magma-dag-folder: [/home/weiwentao/workspace/ms-pred/results/dag_canopus_train_public/split_1_rnd1/preds_train_100_inten_corrected/]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd2]
  #    seed: [2]
  #    magma-dag-folder: [results/dag_canopus_train_public/split_1_rnd2/preds_train_100_inten/]

  # -  split-name: [split_1.tsv]
  #    save-dir: [split_1_rnd3]
  #    seed: [3]
  #    magma-dag-folder: [results/dag_canopus_train_public/split_1_rnd3/preds_train_100_inten/]
